from modules.helper import color


def print_usage() -> None:
    print()
    color('[*] Linx 帮助信息', 'blue')
    color('\n基本命令：', 'green')
    color('  help              显示帮助信息', 'white')
    color('  exit/quit         退出程序', 'white')
    color('\n设置命令：', 'green')
    color('  set interface     设置网络接口', 'white')
    color('  set domain        设置目标域名', 'white')
    color('  set port          设置目标端口', 'white')
    color('  set target        设置目标URL', 'white')
    color('\n信息显示：', 'green')
    color('  show interface    显示当前网络接口', 'white')
    color('  show target       显示当前目标', 'white')
    color('  show domain       显示当前域名', 'white')
    color('  show port         显示当前端口', 'white')
    color('\n功能模块：', 'green')
    color('  crawler           网站爬虫模块', 'white')
    color('  scan             端口扫描模块', 'white')
    color('  burp             暴力破解模块', 'white')
    color('  sniffer          网络嗅探模块', 'white')
    color('  wifi             无线网络模块', 'white')
    color('  rpc              远程调用模块', 'white')
    print()
    color('[*] 使用 <模块名> show 查看具体模块的帮助信息', 'yellow')
    print()
